version: 2.1

orbs:
    codecov: codecov/codecov@1.0.5
    browser_tools: circleci/browser-tools@0.1.3

defaults: &defaults
  working_directory: ~/ngx-fileupload
  docker:
      - image: circleci/node:10.14.1-browsers

aliases:
  - &filter_master
      branches:
        only: master

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: ngx-fileupload-{{ .Branch }}-{{ checksum "src/package-lock.json" }}
      - run:
          name: "install packages"
          command: cd src && npm install && npm i webdriver-manager
      - save_cache:
          key: ngx-fileupload-{{ .Branch }}-{{ checksum "src/package-lock.json" }}
          paths:
            - "src/node_modules"
      - persist_to_workspace:
          root: ~/ngx-fileupload
          paths:
            - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ngx-fileupload
      - run:
          name: "run lint"
          command: cd src && npm run lint -- ngx-fileupload
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ngx-fileupload
      - run:
          name: "run unit tests"
          command: cd src && npm run test -- ngx-fileupload --watch=false --code-coverage
      - persist_to_workspace:
          root: ~/ngx-fileupload
          paths: 
            - ./src/coverage
  e2e:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ngx-fileupload
      - browser_tools/install-chrome: 
          replace-existing: true
      - run:
          name: "run e2e tests"
          command: cd src && npm run pretest:e2e && npm run e2e
  coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ngx-fileupload
      - codecov/upload:
          file: "./src/coverage/ngx-fileupload/lcov.info"

workflows:
  version: 2.1
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - e2e:
          requires:
            - install
      - coverage:
          requires:
            - test
